
structure ExecutionBarry : EXECUTION =
  struct
    structure Compile = CompileBarry
    structure TopdecGrammar = PostElabTopdecGrammar
    structure PP = PrettyPrint
    structure Labels = AddressLabels
    structure DecGrammar = TopdecGrammar.DecGrammar
    structure CompileBasis = CompileBasisBarry

    fun die s = (print ("ExecutionBarry.Die: " ^ s); raise Fail s)

    val backend_name = "Barry"
    val backend_longname = "Barry - the Standard ML barifier"

    type CompileBasis = CompileBasis.CompileBasis
    type CEnv = CompilerEnv.CEnv
    type Env = CompilerEnv.ElabEnv
    type strdec = TopdecGrammar.strdec
    type strexp = TopdecGrammar.strexp
    type funid = TopdecGrammar.funid
    type strid = TopdecGrammar.strid
    type lab = Labels.label
    type linkinfo = {unsafe:bool}
    type target = Compile.target

    val pr_lab = Labels.pr_label
    val dummy_label = Labels.new()
    val code_label_of_linkinfo : linkinfo -> lab = fn _ => dummy_label
    val imports_of_linkinfo : linkinfo -> (lab list * lab list) = fn _ => (nil,nil)
    val exports_of_linkinfo : linkinfo -> (lab list * lab list) = fn _ => (nil,nil)
    fun unsafe_linkinfo (li: linkinfo) : bool =  #unsafe li

    (* Hook to be run before any compilation *)
    val preHook = Compile.preHook

    (* Hook to be run after all compilations (for one compilation unit) *)
    val postHook = Compile.postHook

    datatype res = CodeRes of CEnv * CompileBasis * target * linkinfo
                 | CEnvOnlyRes of CEnv
    fun compile fe (ce,CB,strdecs,vcg_file) =
      let val (cb,()) = CompileBasis.de_CompileBasis CB
      in
	case Compile.compile fe (ce, cb, strdecs)
	  of Compile.CEnvOnlyRes ce => CEnvOnlyRes ce
	   | Compile.CodeRes(ce,cb,target,safe) =>
	    let
		(* to use not(safe) below, we should compile lvars, etc., to labels and
		 * use imports and exports appropriately *)
		val linkinfo : linkinfo = {unsafe=true(*not(safe)*)}
		val CB = CompileBasis.mk_CompileBasis(cb,())
	    in CodeRes(ce,CB,target,linkinfo)
	    end
      end
    val generate_link_code = NONE
    fun emit a = Compile.emit a

    val op ## = OS.Path.concat infix ##

    local
      val messages_p = Flags.is_on0 "messages"
      fun message f = if messages_p() then print (f()) else ()

      val header = "(* Generated by " ^ backend_longname ^ " *)\n"

      (* A source file is compiled into one unit for the file itself and one
       * for each functor application in it, and emit writes each unit to its
       * own file.  f.sml.unit and f.sml.code3.unit both belong to f.sml. *)
      fun isCode e = size e > 4 andalso String.isPrefix "code" e
                     andalso CharVector.all Char.isDigit (String.extract(e,4,NONE))

      fun is_functor_unit (f:string) : bool =
          case OS.Path.ext (OS.Path.base f) of   (* base drops Compile.unit_ext *)
              SOME e => isCode e
            | NONE => false

      fun source_of (f:string) : string =
          let val b = OS.Path.base f          (* drop Compile.unit_ext *)
          in case OS.Path.ext b of
                 SOME e => if isCode e then OS.Path.base b else b
               | NONE => b
          end

      fun core_of (f:string) : string = source_of f ^ ".sml"

      (* the units are written afresh whenever their source file is compiled,
       * so an up-to-date Core ML file need not be written again *)
      fun uptodate (core,units) =
          let val t = OS.FileSys.modTime core
          in List.all (fn u => Time.<=(OS.FileSys.modTime u, t)) units
          end handle _ => false

      fun copy (os,u) =
          let val is = TextIO.openIn u
                       handle _ => raise Fail ("Barry cannot read the compilation \
                                               \unit " ^ u ^ "; remove the MLB \
                                               \directories and compile again")
          in (TextIO.output(os, TextIO.inputAll is); TextIO.closeIn is)
             handle X => (TextIO.closeIn is; raise X)
          end

      fun write_core (core,units) =
          if uptodate (core,units) then ()
          else let val os = TextIO.openOut core
               in (TextIO.output(os,header);
                   app (fn u => copy (os,u)) units;
                   TextIO.closeOut os;
                   message (fn () => "[wrote Core ML file:\t" ^ core ^ "]\n"))
                  handle X => (TextIO.closeOut os; raise X)
               end

      (* group the units by source file, keeping the order of the groups and
       * the order of the units within a group *)
      fun group (files: string list) : (string * string list) list =
          let fun add ((c,f), nil) = [(c,[f])]
                | add ((c,f), (c',us)::rest) = if c = c' then (c',f::us)::rest
                                               else (c',us) :: add ((c,f),rest)
              val groups = List.foldl add nil (map (fn f => (core_of f,f)) files)
          in map (fn (c,us) => (c,rev us)) groups
          end
    in
      (* the units of one compilation unit are named after the source file
       * itself and after each functor application in it; the Core ML file is
       * named after the source file *)
      fun merge_units nil = ()
        | merge_units (files as f::_) =
          let val f = case List.find (not o is_functor_unit) files of
                          SOME f => f
                        | NONE => f
          in write_core (core_of f, files)
          end

      fun link_files_with_runtime_system files run =
	  let val groups = group files
	      val () = app write_core groups
	      val mlb_file = run ^ ".mlb"
	      val os = TextIO.openOut mlb_file
	  in
	      (TextIO.output(os, header ^ "\n");
	       app (fn (c,_) => TextIO.output(os, c ^ "\n")) groups;
	       TextIO.closeOut os;
	       print("[Created file " ^ mlb_file ^ "]\n"))
	      handle X => (TextIO.closeOut os; raise X)
	  end
    end

    val be_rigid = true

    fun mlbdir () = "MLB" ## "Barry"

    val pu_linkinfo =
	Pickle.convert (fn b => {unsafe=b},
			fn {unsafe=b} => b)
	Pickle.bool

    fun create_repl_runtime _ _ = die "create_repl_runtime: not implemented"
    val generate_repl_init_code = NONE

    fun mk_sharedlib _ = die "mk_sharedlib.unimplemented"

    datatype cval = datatype Compile.cval
    fun retrieve_longid _ _ _ : string cval =
        die "retrieve_longid.unimplemented"

    datatype conkind = UNB | ENU | BOX
    type tyvar = CompilerEnv.tyvar
    type Type = CompilerEnv.Type
    type coninfo = string * (tyvar list * Type)
    fun tyname_reps (CB: CompileBasis) (tn: TyName.TyName) : coninfo list option =
        die "tyname_reps.unimplemented"

    fun export_basis_js () = false
    val toJSString : (string -> string) option = NONE

    val mk_repl_runtime = NONE

  end
